title: Project 2048
description: A Flask-based 2048 game with AWS Elastic Beanstalk deployment guide
theme: just-the-docs

url: https://siddharth1254.github.io/2048

aux_links:
  GitHub Repository: https://github.com/Siddharth1254/2048

# Exclude non-Jekyll files from the build
exclude:
  - projects/
  - README.md
  - LICENSE
